from typing import Any

from googleapiclient.http import HttpRequest  # pyright: ignore[reportMissingTypeStubs]

from ..errors import eprint
from ..info import print_info
from ..models import ContentBody, Form
from ._resource import FormResource, FormsService
from .service_init import run_service


def _setup_form(
    form: Form, form_content: ContentBody, *, service: FormsService
) -> Form | None:
    """
    Completes the initialization of a Google form using the `Form` object
    returned from the `create_form` function which stores the url and form id of
    the created form. The initialization is completed by updating the form's
    contents using the argument passed in through the parameter
    `form_content`. If the function completes successfully, the `Form` object
    passed in is returned; else None is returned.

    :param form: (Form) - a `Form` object, generated by the `create_form`
                   function that stores the metadata of the partially
                   initialized form whose initialization is completed when
                   this function runs successfully.
    :param form_content: (ContentBody) - A typed dictionary with a single key
                           `requests` which stores a list of a nested structure
                           containing typed dictionaries.
    :param service: (FormResource) - FormResource object that provides the
                     forms() method to create a form resource which is used to
                     update the form using the batchUpdate() method.
    :return: (Form | None) - the `Form` object passed in is returned if the
             function completes successfully else None is returned.
    """

    form_id: str = form.uuid
    form_resource: FormResource = service.forms()
    request_body: dict[str, Any] = form_content.model_dump(exclude_none=True)
    try:
        request: HttpRequest = form_resource.batchUpdate(
            formId=form_id, body=request_body
        )
        request.execute()  # pyright: ignore [reportUnknownMemberType]
        print_info(
            f"Form with name={form.name}, title={form.title} and url={form.url} setup successfully.\n"
        )
        return form
    except Exception as e:
        eprint(f"Fatal error occurred while updating form. Error encountered is {e}\n")
        return None


def run_setup_form(form: Form, form_content: ContentBody) -> Form | None:
    """Completes the initialization of a Google form using the `Form` object
    returned from the `run_create_form` function which stores the url and form
    id of the created form. The initialization is completed by updating the
    form's contents using the argument passed in through the parameter
    `form_content`. If the function completes successfully, the `Form` object
    passed in is returned; else None is returned.

    :param form: (Form) - a `Form` object, generated by the `run_create_form`
                   function that stores the metadata of the partially
                   initialized form whose initialization is completed when
                   this function runs successfully.
    :type form: Form
    :param form_content: (ContentBody) - A typed dictionary with a single key
                            `requests` which stores a list of a nested structure
                            containing typed dictionaries. in other words, the
                            structure of ContentBody could be broken down as

        - ContentBody
            - "requests": list[Content]

        - Content: is a Pydantic Model whose contents can be filled using
                   completion context menus
    :type form_content: ContentBody

    :return: (Form | None) - a `Form` object which is identical to the one passed in through
             the `form` argument and is returned if the function completes
             successfully else None is returned.
    :rtype: Form | None
    """

    def _run_service(service: FormsService) -> Form | None:
        return _setup_form(form, form_content, service=service)

    return run_service(
        api="forms",
        version="v1",
        func=_run_service,
    )
